export default {
    ADD_CALC: "ADD_CALC",
    REMOVE_CALC: "REMOVE_CALC",
    MULTIPLY_CALC_TOTAL: "MULTIPLY_CALC_TOTAL",
    ADD_CALC_TOTAL: "ADD_CALC_TOTAL",
    SUBTRACT_CALC_TOTAL: "SUBTRACT_CALC_TOTAL",
    DIVIDE_CALC_TOTAL: "DIVIDE_CALC_TOTAL",
    ADJUST_STATE: "ADJUST_STATE"
}